config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'
  get 'resume' => 'landings#resume'
  root 'landings#index'

  resources :user_settings
  devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords"
    }, skip: [
      :sessions,
      :registrations
    ]

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end


  # API_SLUG APP
  namespace :api_slug do
    resources :api_keys do
      member do
        post :reset
      end
    end
  end
  resources :api_slug
  # END API_SLUG
  resources :converters, only: [:index] do
    collection do
      post :xml
    end
  end

end

app/models/user_setting.rb
class UserSetting < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_user_setting, only: [:show, :edit, :update, :destroy]

  # GET /user_settings
  # GET /user_settings.json
  def index
    @user_settings = UserSetting.all
  end

  # GET /user_settings/1
  # GET /user_settings/1.json
  def show
  end

  # GET /user_settings/new
  def new
    @user_setting = UserSetting.new
  end

  # GET /user_settings/1/edit
  def edit
  end

  # POST /user_settings
  # POST /user_settings.json
  def create
    @user_setting = UserSetting.new(user_setting_params)
    @user_setting.user = current_user

    respond_to do |format|
      if @user_setting.save
        format.html { redirect_to @user_setting, notice: 'User setting was successfully created.' }
        format.json { render :show, status: :created, location: @user_setting }
      else
        format.html { render :new }
        format.json { render json: @user_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_settings/1
  # PATCH/PUT /user_settings/1.json
  def update
    respond_to do |format|
      if @user_setting.update(user_setting_params)
        format.html { redirect_to @user_setting, notice: 'User setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_setting }
      else
        format.html { render :edit }
        format.json { render json: @user_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_settings/1
  # DELETE /user_settings/1.json
  def destroy
    @user_setting.destroy
    respond_to do |format|
      format.html { redirect_to user_settings_url, notice: 'User setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_setting
      @user_setting = UserSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_setting_params
      params.require(:user_setting).permit(:user_id, :account)
    end
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/user_settings/_form.html.erb
<%= form_for @user_setting, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :account, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :account, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  user_settings_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/user_settings/edit.html.erb
<%- model_class = UserSetting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => UserSetting %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_settings/index.html.erb
<%- model_class = UserSetting -%>
<div class="page-header">
  <h1><%=t '.title', :default => UserSetting %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:account) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_settings.each do |user_setting| %>
      <tr>
        <td><%= user_setting.id %></td>
        <td><%= user_setting.account %></td>
        <td><%=l user_setting.created_at, format: :long %></td>
        <td>
          <%= link_to user_setting_path(user_setting), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to user_setting_path(user_setting), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_setting_path,
            :class => 'btn btn-primary' %>

app/views/user_settings/new.html.erb
<%- model_class = UserSetting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => UserSetting %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_settings/show.html.erb
<%- model_class = UserSetting -%>
<div class="page-header">
  <h1><%=t '.title', :default => UserSetting %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:account) %></dt>
      <dd><pre class="prettyprint"><%= @user_setting.account %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_settings_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_setting_path(@user_setting), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_setting_path(@user_setting),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>